import { Format } from "./EFormat";
import { Characters } from "./ICharacters";
import { Creators } from "./ICreators";
import { DateElement } from "./IDateElement";
import { DiamondCode } from "./IDiamondCode";
import { Price } from "./IPrice";
import { Series } from "./ISeries";
import { Stories } from "./IStories";
import { TextObject } from "./ITextObject";
import { Thumbnail } from "./IThumbNail";

export interface Result {
  id?: number;
  digitalId?: number;
  title?: string;
  issueNumber?: number;
  variantDescription?: string;
  description?: null | string;
  modified?: string;
  isbn?: string;
  upc?: string;
  diamondCode?: DiamondCode;
  ean?: string;
  issn?: string;
  format?: Format;
  pageCount?: number;
  textObjects?: TextObject[];
  resourceURI?: string;
  urls?: URL[];
  series?: Series;
  variants?: Series[];
  collections?: any[];
  collectedIssues?: Series[];
  dates?: DateElement[];
  prices?: Price[];
  thumbnail?: Thumbnail;
  images?: Thumbnail[];
  creators?: Creators;
  characters?: Characters;
  stories?: Stories;
  events?: Characters;
}
